### ISSUE TITLE
Manually save detection in InfraView

### ISSUE THREAD

**Issue by fdannemanndugick** [LANL-Seismoacoustics/infrapy#10]
use right click or something similar to manually save a datapoint from beamforming as a detection.

**Comment by jwebster-LANL** [comment]
Good news:  I added this, apologies for it taking so long.  If you Control + left click (Command on a mac) on a point, the app will generate a detection at the nearest point and will pop up a window for you to enter more information

Bad news:  It's on the update_pyqtgraph branch, so if you haven't already check that out and run the update_infrapy.sh script in the base directory.

**Comment by jwebster-LANL** [comment]
this got merged in a while ago, so closing... I probably need to document the functionality somewhere.  For now its a hidden feature
