### ISSUE TITLE
On the crash of Infraview

### ISSUE THREAD

**Issue by chdyxh** [LANL-Seismoacoustics/infrapy#11]
In Infraview, if I load waveform and then clear waveform by cliking "**close tab**" in Trace Info, the infraview will crash and throw the following information: 
`Traceback (most recent call last):
  File "/usr/local/infrapy/InfraView/widgets/IPWaveformWidget.py", line 324, in remove_trace
    self.update_streams(self._sts)
  File "/usr/local/infrapy/InfraView/widgets/IPWaveformWidget.py", line 184, in update_streams
    self.statsViewer.setStats(new_stream)
  File "/usr/local/infrapy/InfraView/widgets/IPStatsView.py", line 21, in setStats
    for idx, trace in enumerate(streamList):
TypeError: 'NoneType' object is not iterable`

**Comment by gilbert512** [comment]
I solved the problem by modifying the infrapy.yml file as shown below.

git+ssh://git@github.com/LANL-Seismoacoustics/pisces.git@old_sqlalchemy#egg=pisces

==> git+https://github.com/LANL-Seismoacoustics/pisces

**Comment by jkmacc-LANL** [comment]
SQLAlchemy should be fixed hopefully soon in the main Pisces branch and you won't have to do this.

**Comment by jwebster-LANL** [comment]
Marking closed.  I think this is sorted
