### ISSUE TITLE
conda env create problem

### ISSUE THREAD

**Issue by gilbert512** [LANL-Seismoacoustics/infrapy#12]
Try to create conda env with below command.
 'conda env create -f infrapy_env.yml'

However, the following error message is displayed and the installation is no longer possible.

--------------------------
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages
pip-21.2.1           | 1.1 MB    | ################################################################################################################################ | 100%
libopenblas-0.3.17   | 9.2 MB    | ################################################################################################################################ | 100%
ld_impl_linux-64-2.3 | 667 KB    | ################################################################################################################################ | 100%
libgcc-ng-11.1.0     | 6.7 MB    | ################################################################################################################################ | 100%
sphinx-4.1.2         | 1.5 MB    | ################################################################################################################################ | 100%
jupyterlab-3.1.0     | 5.9 MB    | ################################################################################################################################ | 100%
libgfortran5-11.1.0  | 1.7 MB    | ################################################################################################################################ | 100%
jupyter_server-1.10. | 265 KB    | ################################################################################################################################ | 100%
libstdcxx-ng-11.1.0  | 4.2 MB    | ################################################################################################################################ | 100%
libgfortran-ng-11.1. | 18 KB     | ################################################################################################################################ | 100%
numpy-1.19.5         | 5.3 MB    | ################################################################################################################################ | 100%
libgomp-11.1.0       | 427 KB    | ################################################################################################################################ | 100%
pandoc-2.14.1        | 12.0 MB   | ################################################################################################################################ | 100%
liblapack-3.9.0      | 11 KB     | ################################################################################################################################ | 100%
libcblas-3.9.0       | 11 KB     | ################################################################################################################################ | 100%
anyio-3.3.0          | 146 KB    | ################################################################################################################################ | 100%
charset-normalizer-2 | 32 KB     | ################################################################################################################################ | 100%
libblas-3.9.0        | 11 KB     | ################################################################################################################################ | 100%
libcurl-7.78.0       | 335 KB    | ################################################################################################################################ | 100%
sqlalchemy-1.4.22    | 2.3 MB    | ################################################################################################################################ | 100%
requests-2.26.0      | 52 KB     | ################################################################################################################################ | 100%
idna-3.1             | 52 KB     | ################################################################################################################################ | 100%
krb5-1.19.2          | 1.4 MB    | ################################################################################################################################ | 100%
bleach-3.3.1         | 111 KB    | ################################################################################################################################ | 100%
Preparing transaction: done
idna-3.1             | 52 KB     | ################################################################################################################################ | 100%
krb5-1.19.2          | 1.4 MB    | ################################################################################################################################ | 100%
bleach-3.3.1         | 111 KB    | ################################################################################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: | Ran pip subprocess with arguments:
['/home/korea/anaconda3/envs/infrapy_env/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/korea/infrapy/condaenv.m_ugwl60.requirements.txt']
Pip subprocess output:
Collecting pisces
  Cloning ssh://****@github.com/LANL-Seismoacoustics/pisces.git (to revision old_sqlalchemy) to /tmp/pip-install-w39wnbh_/pisces_301a5c90dd2a4d76acac76602c553e20
Obtaining file:///home/korea/infrapy (from -r /home/korea/infrapy/condaenv.m_ugwl60.requirements.txt (line 2))

Pip subprocess error:
  Running command git clone -q 'ssh://****@github.com/LANL-Seismoacoustics/pisces.git' /tmp/pip-install-w39wnbh_/pisces_301a5c90dd2a4d76acac76602c553e20
  Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
WARNING: Discarding git+ssh://****@github.com/LANL-Seismoacoustics/pisces.git@old_sqlalchemy#egg=pisces. Command errored out with exit status 128: git clone -q 'ssh://****@github.com/LANL-Seismoacoustics/pisces.git' /tmp/pip-install-w39wnbh_/pisces_301a5c90dd2a4d76acac76602c553e20 Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pisces (unavailable) (from versions: 0.2.4, 0.3.0, 0.3.1, 0.3.2)
ERROR: No matching distribution found for pisces (unavailable)
                                                                                                                                                                         failed

CondaEnvException: Pip failed

**Comment by jkmacc-LANL** [comment]
@gilbert512 Did you resolve your issue?  (I'm sorry I lost track of this.)

**Comment by gilbert512** [comment]
Dear. Jkmacc

Thank you for your interest in my issue.

I solved the problem by modifying the infrapy.yml file as shown below.

***@***.******@***.***_sqlalchemy#egg=pisces

==> git+https://github.com/LANL-Seismoacoustics/pisces <git+https://github.com/LANL-Seismoacoustics/pisces>

Thank you again.

Best regards,
Gilbert
