### ISSUE TITLE
use example data in  the py file "test_yield.py" is missing?

### ISSUE THREAD

**Issue by funny000** [LANL-Seismoacoustics/infrapy#16]
Hi,
   when i use the test_yield.py and find the file "wvfrm_path = "../infrapy-data/hrr-5/*/*.sac"" is missing, can you give me the file or up the file to github? my email is funny_liu@hotmail.com

Thank you.

![image](https://github.com/LANL-Seismoacoustics/infrapy/assets/46562492/d3e22f5c-c24d-4b84-9a94-2ec47f975288)

**Comment by philblom** [comment]
I guess it's not documented appropriately, but there's a separate repo for the infrapy test data: https://github.com/LANL-Seismoacoustics/infrapy-data

Download that and adjust the path accordingly.
