### ISSUE TITLE
Host docs on Read the Docs?

### ISSUE THREAD

**Issue by liamtoney** [LANL-Seismoacoustics/infrapy#6]
It looks like y'all have implemented Sphinx and have everything set up, but the docs aren't hosted online. It could help accessibility to have them easily available online.

We've used [Read the Docs](https://readthedocs.org/) with good success for some UAF packages, i.e. [_rtm_](https://uaf-rtm.readthedocs.io/en/master/). It's free if your repo is already public. The setup is pretty easy if you are able to build/install your package on their server.

I'm happy to assist w/ this if needed!

**Comment by fkdannemann** [comment]
I think @jwebster-LANL is in the process of doing this...tagging him to check on the progress.

**Comment by jwebster-LANL** [comment]
I was looking at using github Pages to get the documentation online, and I really don't like how it works.  I haven't looked at Read the Docs yet, but if it's at all better than Pages, then I'd be happy to give it a shot.

**Comment by jwebster-LANL** [comment]
Liam, I took a shot at this this morning and it seems to have worked well, thanks for the recommendation.
