### ISSUE TITLE
 bisl.summarize(result) not printing correctly

### ISSUE THREAD

**Issue by fdannemanndugick** [LANL-Seismoacoustics/infrapy#8]
@philblom it looks like there are issues with bisl.summarize(result), I am not sure if it is something different in my Python environment but I am getting TypeErrors: 
`TypeError: tuple indices must be integers or slices, not str`

Can you take a look? I can fix if it's truly an error, but do not want to if it isn't an issue.

**Comment by philblom** [comment]
I can run the test_bisl.py example without errors.
If you can, send me the detection list you're using and I'll see if it's an issue unique to some calculation error.
