### ISSUE TITLE
Make repo citeable using Zenodo

### ISSUE THREAD

**Issue by fdannemanndugick** [LANL-Seismoacoustics/infrapy#9]
Hey @jwebster-LANL @philblom @jkmacc-LANL it would be great to be able to cite this repo in some upcoming pubs.  You can give the repo a DOI following these instructions: https://guides.github.com/activities/citable-code/

**Comment by jwebster-LANL** [comment]
seems like a good idea to me.  I started the instructions and got to the point where it says

>  Important! If you want to archive a repository that belongs to an organization on GitHub, you will need to make sure that the organization administrator has enabled third-party access to the Zenodo application.

and I don't have permissions on LANL-Seismoacoustics to do that.  I sent an email to Jonathan and if we can get that bit done, the rest should be straight forward.

**Comment by jkmacc-LANL** [comment]
It looks like @jwebster-LANL can request it.  Stand by.

**Comment by jwebster-LANL** [comment]
I went there and yeah, zenodo was listed and I granted it permission

**Comment by jwebster-LANL** [comment]
Mmmm, I still think I’m missing something.  Trying to follow the directions here…
https://guides.github.com/activities/citable-code/

**Comment by jwebster-LANL** [comment]
Took a bit, but I think I got it set up.  If you go to the infrapy repository - in the readme there is now a Citation section with a link to the zenodo DOI

Cheers
Jeremy
